version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wp_prod
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./config/php.prod.ini:/usr/local/etc/php/conf.d/uploads.ini
